version: '3'
services:

    ganache:
        # FIXME: ganache_1   | Error: EXDEV: cross-device link not permitted, rename '/tmp/tmp-1g6J0UVLVMW56' -> '/ganache/!trie_db!0x41c488877f4bd7f076e7a46574f86eb2e58bb101aad9fd4da0dbf9b60ec8c949'
        # image: trufflesuite/ganache-cli:v6.9.0
        image: trufflesuite/ganache-cli:v6.7.0
        volumes:
            - "${PWD}/docker/data:/ganache:rw"
        user: "1000:1000"
        network_mode: host
        command:
            - "--accounts"
            - "20"
            - "--defaultBalanceEther"
            - "10000"
            - "--mnemonic"
            - "${XBR_HDWALLET_SEED}"
            - "--gasLimit"
            - "10000000"
            - "--gasPrice"
            - "8000000000"
            - "--port"
            - "1545"
            - "--networkId"
            - "5777"
            - "--db"
            - "/ganache"

    truffle:
        depends_on:
          - ganache
        image: crossbario/truffle
        build:
          context: docker
        command: bash
        stdin_open: true
        tty: true
        network_mode: host
        volumes:
          - ./:/code:rw

    crossbar:
        depends_on:
          - ganache
        image: crossbario/crossbarfx:latest
        # UID:GID => id -u, id -g
        user: "1000:1000"
        network_mode: host
        #ports:
        #    - "8080:8080"
        volumes:
            - "${PWD}/teststack/crossbar:/node"
