version: '3'
services:

    ganache:
        # https://github.com/trufflesuite/ganache-cli/issues/593
        # image: trufflesuite/ganache-cli:v6.2.4
        # image: trufflesuite/ganache-cli:v6.5.1
        image: trufflesuite/ganache-cli:v6.7.0
        # UID:GID => id -u, id -g
        user: "1000:1000"
        network_mode: host
        #ports:
        #    - "8545:8545"
        #    - "7545:8545"
        volumes:
            # mount a data location from the host into the container - read-write
            - "${PWD}/teststack/ganache/.data:/ganache:rw"
        command:
            # https://github.com/trufflesuite/ganache-cli#using-ganache-cli
            - "--accounts"
            - "20"
            - "--defaultBalanceEther"
            - "10000"
            # - "--deterministic"
            - "--mnemonic"
            - "myth like bonus scare over problem client lizard pioneer submit female collect"
            - "--gasLimit"
            - "0xfffffffffff"
            - "--gasPrice"
            - "1"
            - "--port"
            - "1545"
            - "--networkId"
            - "5777"
            - "--db"
            - "/ganache"

    # docker attach
    truffle:
        depends_on:
          - ganache
        image: crossbario/truffle
        build:
          context: docker
        command: bash
        stdin_open: true
        tty: true
        network_mode: host
        volumes:
          - ./:/code:rw

    crossbar:
        depends_on:
          - ganache
        image: crossbario/crossbarfx:latest
        # UID:GID => id -u, id -g
        user: "1000:1000"
        network_mode: host
        #ports:
        #    - "8080:8080"
        volumes:
            - "${PWD}/teststack/crossbar:/node"
